### ISSUE TITLE
Not working in combination with the 'Hiding Navigation'

### ISSUE THREAD

**Issue by rogiervanroon** [CodyHouse/cd-chameleonic-header-changelog#1]
I tried to combine this effect with the Hiding Navigation: https://codyhouse.co/ds/components/app/hiding-navigation

`<section class="position-relative js-cha-section">`
`	<div class="cha-header-clip js-cha-header-clip">`
`		<header class="f-header js-f-header hide-nav js-hide-nav js-hide-nav--main cha-header js-cha-header" data-mobile-trigger='js-anim-menu-btn'>`
`			...`
`		</header>`
`	</div>`
`</section>`

It seems the hiding classes/js are not fired as soon as the header is wrapped as a  chameleonic header.

**Comment by sebastiano-guerriero** [comment]
Hi there! I'm afraid the Chameleonic Header is not compatible with the Hiding Navigation, because the "chameleonic" effect is achieved duplicating the navigation and using the clip-path CSS property. Both things will conflict with the behaviour of the hiding navigation.
