### ISSUE TITLE
Potential conflict between chameleonic header and section divider components?

### ISSUE THREAD

**Issue by mcmanimie** [CodyHouse/cd-chameleonic-header-changelog#2]
I can't seem to resolve a visible line that appears as you roll the chameleonic header over one of the section divider components.  

![Example](https://www.dropbox.com/s/kldtpwp3c9hyw4a/line.png?raw=1)

Best to just show you:  https://compassionate-wiles-9b96c9.netlify.app/

**Comment by claudia-romano** [comment]
Hi there, sorry for the late reply.
Those components are not compatible at the moment. The chameleonic header uses the CSS clip-path property while the section divider uses an inline SVG element (which does not properly clip the header).
