### ISSUE TITLE
Possible z-index issue

### ISSUE THREAD

**Issue by rule13** [CodyHouse/cd-chameleonic-header-changelog#3]
Elements flow on top of the chameleon header as the page scrolls.  

I am experiencing issues with the following components:

Link Effects (links with effect flow on top of chameleon header)
Feature v12 (images and CTA button flow on top of chameleon header)
Feature v14 (images and all text flows on top of chameleon header)
Text Points - Counter (all text flows on top of chameleon header)

I suspect this is a z-index thing... but I am unable to figure it out. Increasing the z-index of the chameleon header does not seem to work.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up!

You will need to change the z-index of the `.cha-header-clip` element (which is the wrapper of the header). You can use the `--z-index-header` variable for that:
https://codyhouse.co/ds/docs/framework/z-index

We'll make sure to update the component to include that by default. Thanks!

**Comment by claudia-romano** [comment]
The component has been updated to fix this issue. Cheers!
